const catalogAllCar = [
    {
        categoryCar: 'diversity_car',
        id: 'car1',
        idIzbr: 'car01',
        hrefLink: "skodaRapid.html",
        nameFilter: 'skoda',
        name: 'Skoda',
        model: "Rapid",
        price: 32396,
        img: '../img/auto/skodarap1.jpg',
        year: "2019 г",
        capacity: "1598 см<sup>3</sup>",
        span_descr: "бензин,",
        span_descrCity: "механика"
    },
    {
        categoryCar: 'diversity_car',
        id: 'car2',
        idIzbr: 'car02',
        hrefLink: "skodaRapid.html",
        name: 'Skoda',
        nameFilter: 'skoda',
        model: "Octavia",
        price: 48574,
        img: '../img/auto/skodaact.png',
        year: "2019 г",
        capacity: "1598 см<sup>3</sup>",
        span_descr: "дизель,",
        span_descrCity: "автомат"
    },
    {
        categoryCar: 'diversity_car',
        id: 'car3',
        idIzbr: 'car03',
        hrefLink: "skodaRapid.html",
        nameFilter: 'skoda',
        name: 'Skoda',
        model: "Kodiaq",
        price: 71919,
        img: '../img/auto/skodakodiaq.jpg',
        year: "2020 г",
        capacity: "1395 см<sup>3</sup>",
        span_descr: "бензин,",
        span_descrCity: "робот"
    },
    {
        categoryCar: 'diversity_car',
        id: 'car4',
        idIzbr: 'car04',
        hrefLink: "skodaRapid.html",
        nameFilter: 'audi',
        name: 'Audi',
        model: "A3",
        price: 62982,
        img: '../img/auto/audia3_1.jpg',
        year: "2020 г",
        capacity: "1395 см<sup>3</sup>",
        span_descr: "бензин,",
        span_descrCity: "робот"
    },
    {
        categoryCar: 'diversity_car',
        id: 'car5',
        idIzbr: 'car05',
        hrefLink: "skodaRapid.html",
        nameFilter: 'audi',
        name: 'Audi',
        model: "A6",
        price: 209791,
        img: '../img/auto/audia6_1.jpg',
        year: "2019 г",
        capacity: "2995 см<sup>3</sup>",
        span_descr: "бензин,",
        span_descrCity: "робот"
    },
    {
        categoryCar: 'diversity_car',
        id: 'car6',
        idIzbr: 'car06',
        hrefLink: "skodaRapid.html",
        nameFilter: 'audi',
        name: 'Audi',
        model: "A8",
        price: 281062,
        img: '../img/auto/audia8_1.jpg',
        year: "2019 г",
        capacity: "2995 см<sup>3</sup>",
        span_descr: "бензин,",
        span_descrCity: "автомат"
    },
    {
        categoryCar: 'diversity_car',
        id: 'car7',
        idIzbr: 'car07',
        hrefLink: "skodaRapid.html",
        nameFilter: 'audi',
        name: 'Audi',
        model: "A3",
        price: 54358,
        img: '../img/auto/audia3_2.jpg',
        year: "2018 г",
        capacity: "1395 см<sup>3</sup>",
        span_descr: "бензин,",
        span_descrCity: "робот"
    },
    {
        categoryCar: 'diversity_car',
        id: 'car8',
        idIzbr: 'car08',
        hrefLink: "skodaRapid.html",
        nameFilter: 'bmw',
        name: 'BMW',
        model: "X7",
        price: 258944,
        img: '../img/auto/bmwx7_1.jpg',
        year: "2019 г",
        capacity: "2993 см<sup>3</sup>",
        span_descr: "дизель,",
        span_descrCity: "автомат"
    },
    {
        categoryCar: 'diversity_car',
        id: 'car9',
        idIzbr: 'car90',
        hrefLink: "skodaRapid.html",
        nameFilter: 'bmw',
        name: 'BMW',
        model: "X6",
        price: 142803,
        img: '../img/auto/bmwx6_1.jpg',
        year: "2019 г",
        capacity: "2993 см<sup>3</sup>",
        span_descr: "дизель,",
        span_descrCity: "автомат"
    },
    {
        categoryCar: 'diversity_car',
        id: 'car11',
        idIzbr: 'car011',
        hrefLink: "skodaRapid.html",
        nameFilter: 'ferrari',
        name: 'Ferrari',
        model: "488 GTB",
        price: 17101000,
        img: '../img/auto/ferr1.jpg',
        year: "2019 г",
        capacity: "3902 см<sup>3</sup>",
        span_descr: "бензин,",
        span_descrCity: "робот"
    },
    {
        categoryCar: 'diversity_car',
        id: 'car172',
        idIzbr: 'car0172',
        hrefLink: "skodaRapid.html",
        nameFilter: 'ferrari',
        name: 'Ferrari',
        model: "GTC4 Lusso",
        price: 17101000,
        img: '../img/auto/ferr2.jpg',
        year: "2020 г",
        capacity: "6262 см<sup>3</sup>",
        span_descr: "бензин,",
        span_descrCity: "робот"
    },
    {
        categoryCar: 'diversity_car',
        id: 'car112',
        idIzbr: 'car0112',
        hrefLink: "skodaRapid.html",
        nameFilter: 'bmw',
        name: 'BMW',
        model: "i4",
        price: 17101000,
        img: '../img/auto/bmw_i4.jpeg',
        year: "2020 г",
        capacity: "4021 см<sup>3</sup>",
        span_descr: "бензин,",
        span_descrCity: "робот"
    },
    {
        categoryCar: 'jeep',
        id: 'car13',
        idIzbr: 'car013',
        hrefLink: "skodaRapid.html",
        nameFilter: 'kia',
        name: 'KIA',
        model: "Rent A Car",
        price: 587145,
        img: '../img/auto/kia_1.jpg',
        year: "2020 г",
        capacity: "4875 см<sup>3</sup>",
        span_descr: "бензин,",
        span_descrCity: "автомат"
    },
    {
        categoryCar: 'jeep',
        id: 'car14',
        idIzbr: 'car014',
        hrefLink: "skodaRapid.html",
        nameFilter: 'kia',
        name: 'KIA',
        model: "Bulgaria",
        price: 127584,
        img: '../img/auto/kia_2.jpg',
        year: "2020 г",
        capacity: "4875 см<sup>3</sup>",
        span_descr: "бензин,",
        span_descrCity: "автомат"
    },
    {
        categoryCar: 'jeep',
        id: 'car230',
        idIzbr: 'car0230',
        hrefLink: "skodaRapid.html",
        nameFilter: 'skoda',
        name: 'Skoda',
        model: "Bulgaria",
        price: 127584,
        img: '../img/auto/kia_2.jpg',
        year: "2020 г",
        capacity: "4875 см<sup>3</sup>",
        span_descr: "бензин,",
        span_descrCity: "автомат"
    },
    {
        categoryCar: 'jeep',
        id: 'car10',
        idIzbr: 'car010',
        hrefLink: "skodaRapid.html",
        nameFilter: 'bmw',
        name: 'BMW',
        model: "X6",
        price: 85142,
        img: '../img/auto/bmwx6_2.jpg',
        year: "2018 г",
        capacity: "2993 см<sup>3</sup>",
        span_descr: "бензин,",
        span_descrCity: "механика"
    },
    {
        categoryCar: 'jeep',
        id: 'car15',
        idIzbr: 'car015',
        hrefLink: "skodaRapid.html",
        nameFilter: 'isuzu',
        name: 'Isuzu',
        model: "D-Max",
        price: 17589658,
        img: '../img/auto/isuzu_1.jpg',
        year: "2019 г",
        capacity: "7025 см<sup>3</sup>",
        span_descr: "дизель,",
        span_descrCity: "автомат"
    },
    {
        categoryCar: 'jeep',
        id: 'car178',
        idIzbr: 'car0178',
        hrefLink: "skodaRapid.html",
        hrefLink: "skodaRapid.html",
        nameFilter: 'suzuki',
        name: 'Suzuki',
        model: "Grand Vitara",
        price: 968325,
        img: '../img/auto/suzuki_jeep_1.png',
        year: "2019 г",
        capacity: "2057 см<sup>3</sup>",
        span_descr: "бензин,",
        span_descrCity: "автомат"
    },
    {
        categoryCar: 'jeep',
        id: 'car16',
        idIzbr: 'car016',
        hrefLink: "skodaRapid.html",
        nameFilter: 'mersedez',
        name: 'Mersedez',
        model: "GLS",
        price: 587145,
        img: '../img/auto/mers_benz_1.jpg',
        year: "2020 г",
        capacity: "2687 см<sup>3</sup>",
        span_descr: "бензин,",
        span_descrCity: "автомат"
    },
    {
        categoryCar: 'jeep',
        id: 'car17',
        idIzbr: 'car017',
        hrefLink: "skodaRapid.html",
        nameFilter: 'mersedez',
        name: 'Mersedez',
        model: "Benz GL-Class",
        price: 587145,
        img: '../img/auto/mers_benz_1.jpg',
        year: "2009 г",
        capacity: "3578 см<sup>3</sup>",
        span_descr: "бензин,",
        span_descrCity: "механика"
    },
    {
        categoryCar: 'jeep',
        id: 'car18',
        idIzbr: 'car138',
        hrefLink: "skodaRapid.html",
        nameFilter: 'уаз',
        name: 'УАЗ',
        model: "Patriot",
        price: 123654,
        img: '../img/auto/yaz_1.png',
        year: "2017 г",
        capacity: "3578 см<sup>3</sup>",
        span_descr: "бензин,",
        span_descrCity: "механика"
    },
    {
        categoryCar: 'motocircles',
        id: 'car139',
        idIzbr: 'car1309',
        hrefLink: "skodaRapid.html",
        nameFilter: 'suzuki',
        name: 'SUZUKI',
        model: "GX-R 250",
        price: 578632,
        img: '../img/auto/suzuki_1.png',
        year: "2019 г",
        capacity: "223 см<sup>3</sup>",
        span_descr: "бензин",
        span_descrCity: ""
    },
    {
        categoryCar: 'motocircles',
        id: 'car19',
        idIzbr: 'car109',
        hrefLink: "skodaRapid.html",
        nameFilter: 'yamaha',
        name: 'YAMAHA',
        model: "YZF-R6",
        price: 7120,
        img: '../img/auto/yamaha_1.jpg',
        year: "2019 г",
        capacity: "250 см<sup>3</sup>",
        span_descr: "бензин",
        span_descrCity: ""
    },
    {
        categoryCar: 'motocircles',
        id: 'car203',
        idIzbr: 'car2003',
        hrefLink: "skodaRapid.html",
        nameFilter: 'yamaha',
        name: 'YAMAHA',
        model: "YZF-R1",
        price: 7120,
        img: '../img/auto/yamaha_3.jpg',
        year: "2020 г",
        capacity: "250 см<sup>3</sup>",
        span_descr: "бензин",
        span_descrCity: ""
    },
    {
        categoryCar: 'motocircles',
        id: 'car245',
        idIzbr: 'car2045',
        hrefLink: "skodaRapid.html",
        nameFilter: 'yamaha',
        name: 'YAMAHA',
        model: "xsr900",
        price: 7120,
        img: '../img/auto/yamaha_2.jpg',
        year: "2019 г",
        capacity: "175 см<sup>3</sup>",
        span_descr: "бензин",
        span_descrCity: ""
    },
    {
        categoryCar: 'motocircles',
        id: 'car232',
        idIzbr: 'car2032',
        hrefLink: "skodaRapid.html",
        nameFilter: 'kawasaki',
        name: 'KAWASAKI',
        model: "Ninja H2 sx",
        price: 7120,
        img: '../img/auto/kawasaki_1.jpg',
        year: "2018 г",
        capacity: "150 см<sup>3</sup>",
        span_descr: "бензин",
        span_descrCity: ""
    },
    {
        categoryCar: 'motocircles',
        id: 'car233',
        idIzbr: 'car0233',
        hrefLink: "skodaRapid.html",
        nameFilter: 'kawasaki',
        name: 'KAWASAKI',
        model: "7900",
        price: 2485,
        img: '../img/auto/kawasaki_2.jpg',
        year: "2018 г",
        capacity: "135 см<sup>3</sup>",
        span_descr: "бензин",
        span_descrCity: ""
    },
    {
        categoryCar: 'motocircles',
        id: 'car23',
        id: 'car23',
        hrefLink: "skodaRapid.html",
        nameFilter: 'husqvarna',
        name: 'Husqvarna',
        model: "KLK",
        price: 1200,
        img: '../img/auto/husq_2.jpg',
        year: "2016 г",
        capacity: "95 см<sup>3</sup>",
        span_descr: "бензин",
        span_descrCity: ""
    }
]
